### ISSUE TITLE
Issue regarding SRCMD Table Protection

### ISSUE THREAD

**Issue by YazanHussnain-10x** [riscv-non-isa/iopmp-spec#18]
In section 3.5.1, the specs states that:

> In Format 2, MDLCK.md[m] locks both SRCMD_PERM(m).r and SRCMD_PERM(m).w. For MD m≥32, one should use MDLCKH.mdh to lock corresponding bits.

Given that in Format 2, SRCMD_PERM is indexed by `md_num`, this means that both SRCMD_PERM(m) and SRCMD_PERMH(m) are indexed by MD **m**. I believe **MDLCK.md[m]** should lock both **SRCMD_PERM(m).r/w** and **SRCMD_PERMH(m).r/w** not only **SRCMD_PERM(m).r/w**.

**Comment by YazanHussnain-10x** [comment]
@tyshyu @paul-andes

**Comment by tyshyu** [comment]
You are correct. `MDLCK.md` should lock both `SRCMD_PERM(m)` and `SRCMD_PERMH(m)`.

Thank you for your feedback.
