### ISSUE TITLE
Error in MSI write

### ISSUE THREAD

**Issue by YazanHussnain-10x** [riscv-non-isa/iopmp-spec#28]
As the IOPMP now supports MSI, I have a question: what happens if an error occurs during an MSI write? In the case of the IOMMU, if an error occurs during an MSI write, the fault is reported in the fault queue. What is the case for the IOPMP?

Furthermore, In the `ERR_CFG` register, the description of `msi_en` is incomplete:
> It indicates whether the IOPMP triggers MSI.

It should be updated to:
```
It indicates whether the IOPMP triggers MSI or WSI.
```

Alternatively:

```
Indicates the interrupt type:
0: IOPMP triggers WSI
1: IOPMP triggers MSI
```
@tyshyu

**Comment by tyshyu** [comment]
Thank you for your great feedback.

For error in MSI write, we will add a bit in `ERR_REQINFO` for indicating the failed MSI write to V0.9.2-RC3 (next release).

As for description of `ERR_CFG.msi_en`, it will also be completed in V0.9.2-RC3.

**Comment by YazanHussnain-10x** [comment]
Thank you
