### ISSUE TITLE
Missing descriptions for HWCFG0.peis on Section 2.7 Error Reactions

### ISSUE THREAD

**Issue by tyshyu** [riscv-non-isa/iopmp-spec#5]
Hi all,

The description "HWCFG0.peis is 1 if an implementation supports sire, siwe, or sixe." is in spec V0.9.1 but is removed from the latest commits (3369da4 7a76c5d).

`HWCFG0.peis` (IOPMP implements interrupt suppression per entry) is only mentioned in register description of HWCFG0 now.

It would be better if the description is in Section 2.7 like `HWCFG0.pees` (IOPMP implements the error suppression per entry).

**Comment by channingt** [comment]
Thanks for the suggestion. Added back the description, will be available on next release.
