### ISSUE TITLE
Typos and incorrect font type in some descriptions

### ISSUE THREAD

**Issue by tyshyu** [riscv-non-isa/iopmp-spec#6]
Hi all, 

I have read the latest commits (3369da4 7a76c5d) and found some typos and incorrect font type in some descriptions in the latest commits:

1. Some "SID" words haven't be renamed to RRID.
Details are from IOPMP TG mailing list: https://lists.riscv.org/g/tech-iopmp/message/277

3.  In Section 2.7 Error Reactions

```
    Return                                                                          .
    VVVVVV                                                                          V
 2. Retrun bus error (or a decode error) or not with an implementation-defined value;
```

4. `ERR_REQINFO.v` should be `*ERR_REQINFO.v*` at https://github.com/riscv-non-isa/iopmp-spec/blob/main/chapter2.adoc?plain=1#L80 (Section 2.7 Error Reactions)

5. `MDCFG(m).t` and `MDCFG(m+1).t` should be `*MDCFG(_m_).t*` and `*MDCFG(_m_+1).t*` at https://github.com/riscv-non-isa/iopmp-spec/blob/main/chapter3.adoc?plain=1#L19 (Section 3.1 Full Model)

6. `MDCFG(0)`, `MDCFG(j)` and `j` should be `*MDCFG(0)*`, `*MDCFG(_j_)*` and `_j_` at https://github.com/riscv-non-isa/iopmp-spec/blob/main/chapter3.adoc?plain=1#L63 (Section 3.3.2 Rapid-K model)

7. `ENTRYLCK.f` should be `*ENTRYLCK.f*` at https://github.com/riscv-non-isa/iopmp-spec/blob/main/chapter3.adoc?plain=1#L85 (Section 3.3.7 Prelocked Configurations)

**Comment by channingt** [comment]
Thanks for you feedback, updated, will be available on next push.
